CREATE TABLE `seoAuditPitches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactId` int,
	`companyName` varchar(255),
	`websiteUrl` varchar(512) NOT NULL,
	`contactEmail` varchar(320),
	`contactName` varchar(255),
	`seoScore` int,
	`seoOnPage` int,
	`seoContent` int,
	`seoTechnical` int,
	`seoTrust` int,
	`topIssues` text,
	`quickWins` text,
	`qualified` int NOT NULL DEFAULT 0,
	`disqualifyReason` varchar(255),
	`annualRevenue` int,
	`employeeCount` int,
	`planName` varchar(64),
	`planPrice` int,
	`demoHtml` text,
	`emailSubject` varchar(512),
	`emailBodyHtml` text,
	`emailBodyText` text,
	`status` enum('pending','running','qualified','not_qualified','email_sent','failed') NOT NULL DEFAULT 'pending',
	`emailSentAt` timestamp,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seoAuditPitches_id` PRIMARY KEY(`id`)
);
