CREATE TABLE `ab_tests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`status` enum('running','completed','cancelled') NOT NULL DEFAULT 'running',
	`variantAId` int NOT NULL,
	`variantBId` int NOT NULL,
	`variantAMetrics` json,
	`variantBMetrics` json,
	`winner` enum('A','B','none'),
	`winnerReason` text,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ab_tests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ad_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`agencyId` int,
	`name` varchar(255) NOT NULL,
	`platform` enum('facebook','google','instagram','linkedin','tiktok') NOT NULL,
	`objective` enum('awareness','traffic','leads','conversions','sales') NOT NULL,
	`status` enum('draft','active','paused','completed','archived') NOT NULL DEFAULT 'draft',
	`targetSuburbs` text,
	`targetDemographics` json,
	`targetInterests` json,
	`targetAudience` json,
	`budgetType` enum('daily','lifetime') DEFAULT 'daily',
	`budgetAmount` int,
	`currency` varchar(3) DEFAULT 'AUD',
	`startDate` timestamp,
	`endDate` timestamp,
	`aiCopy` json,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`conversions` int DEFAULT 0,
	`spend` int DEFAULT 0,
	`revenue` int DEFAULT 0,
	`ctr` varchar(10),
	`cpc` varchar(10),
	`roas` varchar(10),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ad_creatives` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`userId` int NOT NULL,
	`platform` enum('facebook','google','instagram','linkedin','tiktok') NOT NULL,
	`type` enum('image','video','carousel','text') NOT NULL DEFAULT 'text',
	`headline` varchar(255),
	`description` text,
	`primaryText` text,
	`callToAction` varchar(64),
	`imageUrl` varchar(1024),
	`landingUrl` varchar(1024),
	`isSaved` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_creatives_id` PRIMARY KEY(`id`)
);
